tasks:
  - init: |
      echo 'TODO: build project'
      pip install -U pip setuptools wheel pip-tools requests poetry
      pip install -U pip yapf autoflake isort coverage 
      sudo apt-get install lynx direnv poetry -y
    command: |
      echo 'TODO: start app'
      poetry run python -m pip freeze > requirements.in
      poetry run python -m pip-compile
      rm requirements.in
      poetry run python -m pip install -U -r requirements.txt
      printf "#!/usr/bin/env bash \nexport z='EasyQuest'" > .envrc;direnv allow
      echo 'TODO:Good $z'
